### ISSUE TITLE
Changnig script post_upgrade.sh name

### ISSUE THREAD

**Issue by sonicaj** [jsegaert/iocage-plugin-mineos#1]
Hello @jsegaert. So we are introducing a change in iocage which affects existing plugins using `post_upgrade.sh` script which is executed after a plugin is updated via `iocage update`. Now `post_upgrade.sh` conflicts with the name `update` and thus is confusing in general, so we have decided to have this script renamed to `post_update.sh`. Can you please reflect these changes here in your repo ? Because updates won't work otherwise. Thanks!

**Comment by sonicaj** [comment]
@jsegaert another thing, please introduce this change in `master` and `11.3-RELEASE` branch only ( 11.3 doesn't exist right now btw )

**Comment by jsegaert** [comment]
Done; Thanks for letting me know!
