### ISSUE TITLE
rdiff error during backup/update

### ISSUE THREAD

**Issue by LittleDonnieJ** [jsegaert/iocage-plugin-mineos#3]
Tried to update mine OS through truenas and received an error mentioning rdiff-backup. Went through a fresh install and keeping hitting this:

![image](https://user-images.githubusercontent.com/30198297/121235246-437fe880-c85a-11eb-841c-a52ffaad181c.png)

After a little bit of searching, it seems that rdiff-backup has gone through an evolution.

[https://www.freshports.org/sysutils/rdiff-backup/](url)

I think sysutils/py-rdiff-backup needs to be used instead.

**Comment by jsegaert** [comment]
Thank you for your report!

Yes, the default version of python switched from 3.7 to 3.8, and that cause breakage.

This was already fixed upstream in `master` via ix-plugin-hub/iocage-plugin-index#222 but it will only take effect in TrueNAS once this gets merged with the `12.2-RELEASE` branch.

Until then, you can manually install the plugin as per these instructions: 
https://www.truenas.com/community/threads/mineos-plugin-install-error-py37-rdiff-backup-failed-to-install.92941/#post-643938

**Comment by jsegaert** [comment]
This has been merged in the TrueNAS 12.2 branch as per ix-plugin-hub/iocage-plugin-index#235

Note that for Mojang's 1.17 server, you'll have to upgrade java to openjdk16
