### ISSUE TITLE
Default credentials do not work

### ISSUE THREAD

**Issue by DanielOberlechner** [jsegaert/iocage-plugin-mineos#4]
Hi,
i don't know if this here is the right place.
I installed everything via TrueNas Core under the Applications Tab, I clicked install MineOS and selected a jail name.
Documentation says, default credentials are:
mcserver
mcserver

those do not work for me.
Anyone can me explain, how I can resett password, or why even my second install of this plugin does not work with the default credentials?

Kind regards,
Daniel Oberlechner

**Comment by jsegaert** [comment]
Can you provide the exact version of Truenas, so that I can try to reproduce?

**Comment by DanielOberlechner** [comment]
yeah I'use the newest version. freshly installed under a proxmox installation.
Problem is:
When i configured the jail, I only set a jail name.
Nothing else.

Everything else is on standard.
TrueNas Version:
TrueNAS-12.0-U6

There is a user with the name: mcserver
I tried to change via passwd password, no effort. Restarted the mineos service, restarted jail, nothing.
I changed file permission in /var/games/minecraft from root to mcserver:mcserver
no effort so far ...

I'm really desperate to find a solution, but nothing worked for me so far.
Google couldn't help me either.

So I read this repo here is the wirepuller so I created this issue.

**Comment by jsegaert** [comment]
OK, I managed to reproduce this.  It looks like there's a dependency issue between the node-userid module and the latest version of npm.  Until this module gets updated, you can workaround this by downgrading to an older version of node.

Go to the shell in your jail and type the following commands:
```shell
pkg remove -y node npm
pkg install -y node14 npm-node14
./post_install.sh
```
Restart your plugin, and you should be able to logon with those default credentials.  

To change the default password, go to the shell in your jail and execute the command `passwd mcserver` and follow the prompts.

**Comment by DanielOberlechner** [comment]
@jsegaert 
Thank you so much!!
I was going nuts, because I thought I was too stupid to get this thing working.
I tried everything I had on my mind, but nothing worked so far.

Thank you so much!

Can you maybe provide a general fix for this problem?
I would assume after some time more and more people will be running into this issue, or not?

Can they try something to get a good workaround?

Kind regards,
Daniel Oberlechner! 👍

**Comment by jsegaert** [comment]
Done; You should be able to install the patched plugin from the TrueNAS Core WebUI.  I'll keep an eye open for if that module and/or npm get updated so it can use the latest version of node/npm again.

Thank you for your report!
