### ISSUE TITLE
updating javajdk version to 17 for MC 1.18

### ISSUE THREAD

**Issue by rick2909** [jsegaert/iocage-plugin-mineos#6]
My 1.18 server can't start due to not having java JDK version 17. I have followed what is being explained [here](https://discourse.codeemo.com/t/minecraft-1-18-java-1-17/5089/7) but when doing `ln -sf /opt/jdk-17.0.1/bin/java /usr/bin/java` I get `/usr/bin/java: Read-only file system`. 

Since you are the owner of the jail, I thought that I should post it in this repo if not close it and I will post it in the mineOS forums/repo.

**Comment by jsegaert** [comment]
The link you referenced is very Linux-centric, where the MineOS plugin runs on FreeBSD.

There are several links in the upstream repo and in the TrueNAS forums that document this issue and provide a solution, e.g.:

- https://github.com/hexparrot/mineos-node/issues/410
- https://github.com/hexparrot/mineos-node/issues/423
- https://www.truenas.com/community/threads/has-anyone-had-any-success-upgrading-and-using-mineos-with-java16.94150/

In summary, you need to install Java 16 in your plugin jail by running the command `pkg install openjdk16` and then for any 1.18 Minecraft servers, indicate the proper version of Java to use in the `server.config` file (located in /var/games/minecraft/servers/<name_of_your_server>/server.config) by setting/changing the value `java_binary=/usr/local/openjdk16/bin/java`.

Note that if you do not run any _"legacy"_ servers but only 1.18 servers, as an alternative you can just uninstall the older Java versions. If there is only one version of Java installed, there's no need to set that `java_binary=` property.  
In that case, you can also chose to reinstall or update the plugin, as the latest version of the plugin is installing openJDK16.  That being said, some "Forge" mods that use sqlite may run into some SQL errors with the latest packages and Java version.  There's a [thread in the TrueNAS forums](https://www.truenas.com/community/threads/mineos-crash-after-new-server.78239/) for this also.
