### ISSUE TITLE
TRUNAS plugin install error.

### ISSUE THREAD

**Issue by coxdjustin** [jsegaert/iocage-plugin-mineos#7]
I received the below message when trying to install via plugin in TRUNAS Core

Error: mc had a failure Exception: RuntimeError Message: Last 10 lines: fatal: remote error: The unauthenticated git protocol on port 9418 is no longer supported. Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information. Partial plugin destroyed

**Comment by TomJumel** [comment]
Same !

**Comment by jsegaert** [comment]
Thank you for your report.  I'll have this fixed in a bit.
