### ISSUE TITLE
py38-rdiff-backup issues on TrueNAS CORE 12.0-U8.1

### ISSUE THREAD

**Issue by ghost** [jsegaert/iocage-plugin-mineos#9]
When trying to install the MineOS plugin with all the defaults (so all i do is add a jail name and click save), it fails with the below message

![image](https://user-images.githubusercontent.com/9214102/201479446-6267555a-d0f7-4016-ab52-a62f5c1b3755.png)

**Comment by jsegaert** [comment]
Thank you for your report.  I actually [submitted a fix](https://github.com/ix-plugin-hub/iocage-plugin-index/pull/315#issuecomment-1240972493) for this many moons ago, but was told that support for the FreeNAS/TrueNAS 12 plugins was stopped and only the 13 will be maintained going forward.

I just tested that the plugin installs fine under TrueNAS-13.0-U3, so at this point I would recommend to upgrade.

**Comment by ghost** [comment]
Thank you for triaging this and suggesting a work around for this issue. I appreciate it.
